name: Rebuild Edge

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}
    - uses: snapcore/action-build@v1.1.0
      id: snapcraft
    - uses: snapcore/action-publish@v1.1.1
      env:
        SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
      with:
        snap: ${{ steps.snapcraft.outputs.snap }}
        release: edge
